// Code generated by generate-provider-consts.sh; DO NOT EDIT.

package config //nolint

// Provider represents an infrastructure provider.
type Provider string

const (
	ProviderDocker Provider = "docker"
	ProviderCapi Provider = "capi"
	ProviderTalos Provider = "talos"
	ProviderScaleway Provider = "scaleway"
	ProviderAzure Provider = "azure"
	ProviderByot Provider = "byot"
	ProviderKubevirt Provider = "kubevirt"
	ProviderHetzner Provider = "hetzner"
)

// GetAllProviders returns a list of all supported providers without local development providers.
func GetAllProviders() []Provider {
	return []Provider{
		ProviderDocker,
		ProviderCapi,
		ProviderTalos,
		ProviderScaleway,
		ProviderAzure,
		ProviderByot,
		ProviderKubevirt,
		ProviderHetzner,
	}
}
